/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MainWindow.view.MainView', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.mainview',

    requires: [
        'MainWindow.view.MainViewViewModel',
        'Ext.panel.Panel',
        'Ext.tab.Tab',
        'Ext.tab.Bar',
        'Ext.plugin.Responsive'
    ],

    config: {
        plugins: 'viewport'
    },

    viewModel: {
        type: 'mainview'
    },
    responsiveConfig: {
        tall: {
            tabPosition: 'top'
        },
        wide: {
            tabPosition: 'left'
        }
    },
    titleRotation: 0,
    activeTab: 0,
    tabRotation: 0,

    items: [
        {
            xtype: 'panel',
            title: 'Tab 1'
        },
        {
            xtype: 'panel',
            title: 'Tab 2'
        },
        {
            xtype: 'panel',
            title: 'Tab 3'
        }
    ],
    tabBar: {
        xtype: 'tabbar',
        defaultAlign: 'tl-bl',
        minWidth: 100,
        responsiveConfig: {
            
        },
        plugins: [
            {
                ptype: 'responsive'
            }
        ]
    }

});